const mongoose = require("mongoose");

const paymentSchema = mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // What is this payment for
    purpose: {
      type: String,
      enum: ["fees", "admission", "other"],
      required: [true, "Please specify what this payment is for"],
    },

    // Free-text label for "other" or extra context, e.g. "2nd Semester Hostel Fee"
    description: {
      type: String,
    },

    // Amount is stored in the smallest currency unit (kobo) to match Paystack
    amountInKobo: {
      type: Number,
      required: [true, "Amount is required"],
    },

    currency: {
      type: String,
      default: "NGN",
    },

    // Paystack's unique transaction reference — generated by us, sent to Paystack
    reference: {
      type: String,
      required: true,
      unique: true,
    },

    status: {
      type: String,
      enum: ["pending", "success", "failed", "abandoned"],
      default: "pending",
    },

    // Raw response from Paystack after verification, kept for audit/debugging
    paystackData: {
      type: mongoose.Schema.Types.Mixed,
    },

    // Optional link back to whatever this payment settles,
    // e.g. an Admission document ID, so you can mark that record paid too
    relatedTo: {
      type: mongoose.Schema.Types.ObjectId,
      refPath: "relatedModel",
    },
    relatedModel: {
      type: String,
      enum: ["Admission", null],
      default: null,
    },
  },
  { timestamps: true },
);

module.exports = mongoose.model("Payment", paymentSchema);
