const mongoose = require("mongoose");

const paymentSchema = mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // What is this payment for
    purpose: {
      type: String,
      enum: ["applicationFee", "acceptanceFee", "semesterFee", "other"],
      required: [true, "Please specify what this payment is for"],
    },

    // Required for applicationFee/acceptanceFee/semesterFee — determines the amount from the fee schedule
    programLevel: {
      type: String,
      enum: ["Certificate", "Diploma", "Degree", "PGD", "Masters", "PhD"],
    },

    // Required for semesterFee only — which term this payment covers
    session: String, // e.g. "2025/2026"
    semester: {
      type: String,
      enum: ["First Semester", "Second Semester"],
    },

    // Free-text label for "other", e.g. "Hostel Fee"
    description: {
      type: String,
    },

    // Amount is stored in the smallest currency unit (kobo) to match Paystack
    amountInKobo: {
      type: Number,
      required: [true, "Amount is required"],
    },

    currency: {
      type: String,
      default: "NGN",
    },

    // Paystack's unique transaction reference — generated by us, sent to Paystack
    reference: {
      type: String,
      required: true,
      unique: true,
    },

    status: {
      type: String,
      enum: ["pending", "success", "failed", "abandoned"],
      default: "pending",
    },

    // Raw response from Paystack after verification, kept for audit/debugging
    paystackData: {
      type: mongoose.Schema.Types.Mixed,
    },

    // Optional link back to whatever this payment settles,
    // e.g. an Admission document ID, so you can mark that record paid too
    relatedTo: {
      type: mongoose.Schema.Types.ObjectId,
      refPath: "relatedModel",
    },
    relatedModel: {
      type: String,
      enum: ["Admission", null],
      default: null,
    },
  },
  { timestamps: true },
);

module.exports = mongoose.model("Payment", paymentSchema);
